name: CSS API generator

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Build the generated css file
        run: cd css-api; deno run -A build.ts; cd ../
      - uses: stefanzweifel/git-auto-commit-action@v4
