name: CSS API generator

on:
  schedule:
    - cron:  '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Build the generated css file
        run: cd css-api; deno run -A build.ts
      - name: Update files
        uses: test-room-7/action-update-file@v1
        with:
            file-path: '../'
            commit-msg: Update generated css
            github-token: ${{ secrets.GITHUB_TOKEN }}
